name: 'Update rust-toolchain.toml'
description: 'Update your rust-toolchain.toml file and send a PR for it.'
author: 'Alex Kenji Berthold'
inputs:
  minor-version-delta:
    description: 'The delta for the minor version.'
    required: false
    default: 0
  update-patch:
    description: 'Update patch versions.'
    required: false
    default: true
  update-minor:
    description: 'Update minor versions.'
    required: false
    default: true
  toolchain-path:
    description: 'Path to the rust-toolchain file.'
    required: false
    default: './rust-toolchain'
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    required: false
    default: ${{ github.token }}
  base:
    description: 'The GitHub base'
    required: false
    default: ${{ github.head_ref }}
  commit-msg:
    description: 'The message provided with the commit'
    required: false
    default: "rust-toolchain: Update"
  pr-branch:
    description: 'The branch on which the PR is created'
    required: false
    default: "update_rust_toolchain_action"
  pr-title:
    description: 'The title of the PR to be created'
    required: false
    default: "rust-toolchain: Update"
  pr-labels:
    description: 'A comma or newline separated list of labels to set on the Pull Request to be created'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: bash $GITHUB_ACTION_PATH/prepare-environment.sh
      shell: bash
    - run: bash $GITHUB_ACTION_PATH/update-toolchain.sh
      shell: bash
      env:
        TOOLCHAIN_FILE: ${{ inputs.toolchain-path }}
        INPUTS_UPDATE_PATCH: ${{ inputs.update-patch }}
        INPUTS_UPDATE_MINOR: ${{ inputs.update-minor }}
        MINOR_VERSION_DELTA: ${{ inputs.minor-version-delta }}
    - name: Create PR
      uses: peter-evans/create-pull-request@v4.2.2
      with:
        branch: ${{ inputs.pr-branch }}
        delete-branch: true
        title: ${{ inputs.pr-title }}
        labels: ${{ inputs.pr-labels }}
        base: ${{ github.head_ref }}
        token: ${{ inputs.token }}
        body: |
          Automatic change by the [update-rust-toolchain](https://github.com/a-kenji/update-rust-toolchain) Github Action.

          Github Actions will not run workflows on pull requests which are opened by a GitHub Action.

          For examples on how to run workflows on this pr, please go to the [readme](https://github.com/a-kenji/update-rust-toolchain/blob/main/README.md#running-github-actions-on-the-action).



