name: "update-rust-toolchain test"
on:
  workflow_dispatch: # allows manual triggering
  #pull_request:
  #push:
    #branches:
      #- master

jobs:
  simple-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: update-rust-toolchain
      uses: ./.
      with:
        minor-version-delta: 0
        update-minor: true
        update-patch: true
