name: "update-rust-toolchain test"
on:
  workflow_dispatch: # allows manual triggering
  #pull_request:
  #push:
    #branches:
      #- master

jobs:
  simple-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update-rust-toolchain
      uses: ./.
      with:
        minor-version-delta: 0
        update-minor: true
        update-patch: true
