name: "Validate action.yml schema"
on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    paths:
      - 'action.yml'
  push:
    branches: [main]
    paths:
      - 'action.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate YAML
        uses: nwisbeta/validate-yaml-schema@v2.0.0
        with:
          yamlSchemasJson: |
            {
              "https://json.schemastore.org/github-action.json": ["action.yml"]
            }
